version: '3.8'

services: 
    mysql:
      image: mysql:8.0
      restart: unless-stopped
      env_file: ./.env
      environment: 
        - MYSQL_ROOT_PASSWORD=$password
        - MYSQL_DATABASE=$database
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    crate-api:
      depends_on:
        - mysql
      build: ./api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:
        - DB_HOST=mysql
        - DB_USER=$username
        - DB_PASSWORD=$password
        - DB_NAME=$database
        - DB_PORT=$MYSQLDB_LOCAL_PORT
      stdin_open: true
      tty: true
    crate-web-app:
      depends_on: 
        - crate-api
      build: ./web
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $WEB_LOCAL_PORT:$WEB_DOCKER_PORT
    cypress:
      depends_on:
        - crate-api
      image: cypress
      build: ./web/cypress
      command: npm cypress run --headless --config-file ./web/cypress/cypress.config.ts
      volumes:
        - ./e2e/cypress:/app/cypress
        - ./e2e/cypress.config.ts:/app/cypress.config.ts