version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose up --abort-on-container-exit --exit-code-from code/web/cypress
    - run: cat /web/cypress/results/output.xml
workflows:
  build:
    jobs:
    - build
  version: 2.1