version: 2.1
orbs:
  cypress: cypress-io/cypress@2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose up --abort-on-container-exit --exit-code-from cypress
    - run: cat /web/cypress/results/output.xml
workflows:
  build:
    jobs:
    - build
    - cypress/run:
      record: true
  version: 2.1